/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "前端面试文档",
  "description": "",
  "base": "/fe-interview/",
  "headTags": [
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "手写AJAX",
      "frontmatter": {
        "title": "手写AJAX",
        "author": "oliver",
        "date": "2023-03-21"
      },
      "regularPath": "/handwritejs/ajax.html",
      "relativePath": "handwritejs/ajax.md",
      "key": "v-f5feeb98",
      "path": "/handwritejs/ajax.html"
    },
    {
      "title": "深浅拷贝",
      "frontmatter": {
        "title": "深浅拷贝",
        "author": "oliver",
        "date": "2023-03-21"
      },
      "regularPath": "/handwritejs/deep_clone.html",
      "relativePath": "handwritejs/deep_clone.md",
      "key": "v-94c59b40",
      "path": "/handwritejs/deep_clone.html"
    },
    {
      "title": "script中async跟defer有什么区别",
      "frontmatter": {
        "title": "script中async跟defer有什么区别",
        "author": "oliver",
        "date": "2023-3-06"
      },
      "regularPath": "/html/async_and_defer.html",
      "relativePath": "html/async_and_defer.md",
      "key": "v-255d5c94",
      "path": "/html/async_and_defer.html",
      "headers": [
        {
          "level": 2,
          "title": "<script>元素 中async和defer属性的区别",
          "slug": "script-元素-中async和defer属性的区别"
        }
      ]
    },
    {
      "title": "a标签的默认事件禁用后，如何实现跳转？",
      "frontmatter": {
        "title": "a标签的默认事件禁用后，如何实现跳转？",
        "author": "oliver",
        "date": "2023-03-06"
      },
      "regularPath": "/html/a_tag_jump.html",
      "relativePath": "html/a_tag_jump.md",
      "key": "v-0c586464",
      "path": "/html/a_tag_jump.html",
      "headers": [
        {
          "level": 2,
          "title": "a标签的默认事件禁用后，如何实现跳转？",
          "slug": "a标签的默认事件禁用后-如何实现跳转"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-a35b7fcc",
      "path": "/"
    },
    {
      "title": "ajax原理是什么？如何实现？",
      "frontmatter": {
        "title": "ajax原理是什么？如何实现？",
        "author": "oliver",
        "date": "2023-03-22",
        "tags": [
          "js"
        ]
      },
      "regularPath": "/javaScript/ajax.html",
      "relativePath": "javaScript/ajax.md",
      "key": "v-4af3b0ae",
      "path": "/javaScript/ajax.html",
      "headers": [
        {
          "level": 2,
          "title": "AJAX是什么",
          "slug": "ajax是什么"
        },
        {
          "level": 2,
          "title": "实现过程",
          "slug": "实现过程"
        },
        {
          "level": 2,
          "title": "手写",
          "slug": "手写"
        }
      ]
    },
    {
      "title": "HTML语义化",
      "frontmatter": {
        "title": "HTML语义化",
        "author": "oliver",
        "date": "2023-03-06"
      },
      "regularPath": "/html/html_semantization.html",
      "relativePath": "html/html_semantization.md",
      "key": "v-7b4348ae",
      "path": "/html/html_semantization.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是HTML语义化",
          "slug": "什么是html语义化"
        },
        {
          "level": 2,
          "title": "为什么要关注语义化",
          "slug": "为什么要关注语义化"
        }
      ]
    },
    {
      "title": "meta元素都有什么",
      "frontmatter": {
        "title": "meta元素都有什么",
        "author": "oliver",
        "date": "2023-2-28"
      },
      "regularPath": "/html/meta.html",
      "relativePath": "html/meta.md",
      "key": "v-032805e4",
      "path": "/html/meta.html",
      "headers": [
        {
          "level": 2,
          "title": "<meta>：元数据元素",
          "slug": "meta-元数据元素"
        },
        {
          "level": 3,
          "title": "meta元素表示那些不能由其它HTML元相关元素标识的元数据信息，不会显示在页面上，但对于搜索引擎是可读的",
          "slug": "meta元素表示那些不能由其它html元相关元素标识的元数据信息-不会显示在页面上-但对于搜索引擎是可读的"
        }
      ]
    },
    {
      "title": "网站SEO怎么处理",
      "frontmatter": {
        "title": "网站SEO怎么处理",
        "author": "oliver",
        "date": "2023-03-06"
      },
      "regularPath": "/html/seo.html",
      "relativePath": "html/seo.md",
      "key": "v-050d3be8",
      "path": "/html/seo.html",
      "headers": [
        {
          "level": 2,
          "title": "网站SEO怎么处理",
          "slug": "网站seo怎么处理"
        },
        {
          "level": 3,
          "title": "SPA单页面应用SEO解决",
          "slug": "spa单页面应用seo解决"
        }
      ]
    },
    {
      "title": "数组操作",
      "frontmatter": {
        "title": "数组操作",
        "author": "oliver",
        "date": "2023-03-22",
        "tags": [
          "js"
        ]
      },
      "regularPath": "/javaScript/array_cof.html",
      "relativePath": "javaScript/array_cof.md",
      "key": "v-0c208636",
      "path": "/javaScript/array_cof.html",
      "headers": [
        {
          "level": 2,
          "title": "数组方法",
          "slug": "数组方法"
        },
        {
          "level": 3,
          "title": "操作方法",
          "slug": "操作方法"
        },
        {
          "level": 3,
          "title": "排序方法",
          "slug": "排序方法"
        },
        {
          "level": 3,
          "title": "转换方法",
          "slug": "转换方法"
        },
        {
          "level": 3,
          "title": "迭代方法",
          "slug": "迭代方法"
        },
        {
          "level": 2,
          "title": "数组去重",
          "slug": "数组去重"
        },
        {
          "level": 3,
          "title": "值类型数组",
          "slug": "值类型数组"
        },
        {
          "level": 3,
          "title": "对象数组",
          "slug": "对象数组"
        },
        {
          "level": 2,
          "title": "数组扁平化",
          "slug": "数组扁平化"
        }
      ]
    },
    {
      "title": "== 和 ===区别，分别在什么情况使用",
      "frontmatter": {
        "title": "== 和 ===区别，分别在什么情况使用",
        "author": "oliver",
        "date": "2023-03-21",
        "tags": [
          "js"
        ]
      },
      "regularPath": "/javaScript/equal_and_congruent.html",
      "relativePath": "javaScript/equal_and_congruent.md",
      "key": "v-5b3ce4be",
      "path": "/javaScript/equal_and_congruent.html",
      "headers": [
        {
          "level": 2,
          "title": "相等操作符(值相等)",
          "slug": "相等操作符-值相等"
        },
        {
          "level": 3,
          "title": "强制类型转换",
          "slug": "强制类型转换"
        },
        {
          "level": 3,
          "title": "隐式转换相等比较",
          "slug": "隐式转换相等比较"
        },
        {
          "level": 2,
          "title": "全等操作符(类型相等，值也相等)",
          "slug": "全等操作符-类型相等-值也相等"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "js Tags"
      },
      "regularPath": "/tag/js/",
      "key": "v-e8d86dc8",
      "path": "/tag/js/"
    }
  ],
  "themeConfig": {
    "author": "oliver-xie666",
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "Category"
      },
      "tag": {
        "location": 3,
        "text": "Tag"
      }
    },
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "标签",
        "link": "/tag/",
        "icon": "reco-tag"
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "oliver的 JavaScript 博客",
        "items": [
          {
            "text": "Github",
            "link": "https://github.com/oliver-xie666",
            "icon": "reco-github"
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "HTML",
        "path": "/html/meta",
        "collapsable": false,
        "children": [
          {
            "title": "meta元素有什么",
            "path": "/html/meta"
          },
          {
            "title": "<script>元素 中async和defer属性的区别",
            "path": "/html/async_and_defer"
          },
          {
            "title": "HTML语义化",
            "path": "/html/html_semantization"
          },
          {
            "title": "a标签的默认事件禁用后，如何实现跳转",
            "path": "/html/a_tag_jump"
          },
          {
            "title": "网站seo怎么处理",
            "path": "/html/seo"
          }
        ]
      },
      {
        "title": "JavaScript",
        "path": "/javaScript/equal_and_congruent",
        "collapsable": true,
        "children": [
          {
            "title": "相等和全等的区别",
            "path": "javaScript/equal_and_congruent"
          },
          {
            "title": "AJAX的原理及实现",
            "path": "javaScript/ajax"
          },
          {
            "title": "数组操作",
            "path": "javaScript/array_cof"
          }
        ]
      }
    ],
    "subSidebar": "auto"
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    },
    "/en/": {
      "lang": "en-US",
      "path": "/en/"
    }
  }
}