/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "js": {
      "key": "js",
      "scope": "tags",
      "path": "/tag/js/",
      "pageKeys": [
        "v-d40477b8",
        "v-16d4f072",
        "v-32df3582",
        "v-79d7e0fa"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-d40477b8"
      ]
    }
  },
  "categories": {},
  "timeline": {}
}