/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "js": {
      "key": "js",
      "scope": "tags",
      "path": "/tag/js/",
      "pageKeys": [
        "v-5b3ce4be"
      ]
    }
  },
  "categories": {},
  "timeline": {}
}